sources:
  - name: src
    database: sourcedb
    schema: mkmall
    tables: 
      - name: regions 
        description: raw regions
      - name: nations 
        description: raw nations
      - name: customers
        description: raw customers
      - name: orders
        description: raw orders
        config:
          freshness:
            warn_after: {count: 6 , period: day}
            error_after: {count:  153 , period: day}
          loaded_at_field: o_orderdate::timestamp_ntz


      - name: lineitems
        description: raw lineitems
        config:
          freshness:
            warn_after: {count: 62 , period: day}
            error_after: {count:  153 , period: day}
          loaded_at_field: l_commitdate::timestamp_ntz
      
      - name: suppliers
        description: raw suppliers 
            
        